# Generated by Django 3.1.2 on 2020-10-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Покупатель'),
        ),
    ]
